GET http://localhost:7071/api/health HTTP/1.1

###
POST http://localhost:7071/api/conversation HTTP/1.1
Content-Type: application/json

{
    "messages":
    [
        {
            "id": "00152b2c-e8a9-af5a-daad-d815255ddbdb",
            "role": "user",
            "content": "I have a meeting with Morpheus at 2pm on the 22nd. I should learn kung fu by then. Please add the meeting to my Outlook calendar. What does my todo list look like?",
            "date": "2024-08-15T17:45:57.307Z"
        }
    ]
}
###