POST http://localhost:7071/api/chat-post HTTP/1.1
Content-Type: application/json

{
    "messages": "Hello world!",
    "session_id": "1234",
    "user_id": "5678"
}
###
GET http://localhost:7071/api/health HTTP/1.1

###
POST http://localhost:7071/api/test-chat HTTP/1.1
Content-Type: application/json

{
    "messages": [
        {
            "role": "user", 
            "content": "I have a meeting with Morpheus at 2pm on the 22nd. I should learn kung fu by then. Please add the meeting to my Outlook calendar. What does my todo list look like?"
        }
    ]
}
###
POST http://localhost:7071/api/test-chat HTTP/1.1
Content-Type: application/json

{
    "messages": [
        {
            "role": "user", 
            "content": "What does my todo list look like?"
        }
    ]
}